/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krs;

/**
 *
 * @author Lenovo
 */

import javax.swing.table.DefaultTableModel;

public class PerhitunganNilai extends javax.swing.JFrame {

    /**
     * Creates new form KRSMahasiswa
     */
         DefaultTableModel modelmahasiswa;
         InputDataMahasiswa datamahasiswa;
    public PerhitunganNilai() {
        initComponents();
        datamahasiswa = new InputDataMahasiswa();
        viewDataTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelNIM = new javax.swing.JLabel();
        TextFieldNIM = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldAlamat = new javax.swing.JTextField();
        LabelAlamat = new javax.swing.JLabel();
        LabelMataKuliah = new javax.swing.JLabel();
        TextFieldMataKuliah = new javax.swing.JTextField();
        LabelNilai1 = new javax.swing.JLabel();
        LabelNilai3 = new javax.swing.JLabel();
        LabelNilai4 = new javax.swing.JLabel();
        TextFieldNilai4 = new javax.swing.JTextField();
        TextFieldNilai1 = new javax.swing.JTextField();
        LabelNilai = new javax.swing.JLabel();
        TextFieldNilai2 = new javax.swing.JTextField();
        TextFieldNilai3 = new javax.swing.JTextField();
        LabelNilai5 = new javax.swing.JLabel();
        TextFieldNilai5 = new javax.swing.JTextField();
        ButtonSimpan = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableKRS = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNIM.setText("NIM");

        TextFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNIMActionPerformed(evt);
            }
        });

        LabelNama.setText("Nama");

        LabelAlamat.setText("Alamat");

        LabelMataKuliah.setText("Mata Kuliah");

        LabelNilai1.setText("Nilai 1 [10%]");

        LabelNilai3.setText("Nilai 3 - UTS [25%]");

        LabelNilai4.setText("Nilai 4 [15%]");

        TextFieldNilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNilai1ActionPerformed(evt);
            }
        });

        LabelNilai.setText("Nilai 2 [15%]");

        LabelNilai5.setText("Nilai 5 [35%]");

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        TableKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"
            }
        ));
        jScrollPane2.setViewportView(TableKRS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelMataKuliah)
                                .addGap(23, 23, 23)
                                .addComponent(TextFieldMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNIM)
                                    .addComponent(LabelNama)
                                    .addComponent(LabelAlamat))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonHapus)
                                .addGap(16, 16, 16)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNilai1)
                            .addComponent(LabelNilai3)
                            .addComponent(LabelNilai)
                            .addComponent(LabelNilai4)
                            .addComponent(LabelNilai5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNilai1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldNilai4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldNilai3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldNilai5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNilai1)
                            .addComponent(TextFieldNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNilai)
                            .addComponent(TextFieldNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNilai3)
                            .addComponent(TextFieldNilai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNilai4)
                            .addComponent(TextFieldNilai4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNIM)
                            .addComponent(TextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNama)
                            .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAlamat)
                            .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelMataKuliah)
                            .addComponent(TextFieldMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNilai5)
                    .addComponent(TextFieldNilai5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonHapus))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void viewDataTabel(){
        String [] namakolom = {"NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"};
        Object [][] objekmahasiswa = new Object [datamahasiswa.getALL().size()] [3];
        int i = 0;
        for (Mahasiswa mhs: datamahasiswa.getALL()) {
            String arrayMahasiswa[] = {
                mhs.getNIm(),
                mhs.getNama(), 
                mhs.getAlamat(),
                mhs.getMataKuliah(),
                mhs.getNilaiAkhir()
            };
            objekmahasiswa[i] = arrayMahasiswa;
            i++;
        }
        modelmahasiswa = new DefaultTableModel(objekmahasiswa, namakolom);
        TableKRS.setModel(modelmahasiswa);
    }
    
    public void ClearTextField() {
        TextFieldNIM.setText("");
        TextFieldNama.setText("");
        TextFieldAlamat.setText("");
        TextFieldMataKuliah.setText("");
        TextFieldNilai1.setText("");
        TextFieldNilai2.setText("");
        TextFieldNilai3.setText("");
        TextFieldNilai4.setText("");
        TextFieldNilai5.setText("");
    }
    private void TextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNIMActionPerformed

    private void TextFieldNilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNilai1ActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            double nilai1 = Double.parseDouble(TextFieldNilai1.getText());
            double nilai2 = Double.parseDouble(TextFieldNilai2.getText());
            double nilai3 = Double.parseDouble(TextFieldNilai3.getText());
            double nilai4 = Double.parseDouble(TextFieldNilai4.getText());
            double nilai5 = Double.parseDouble(TextFieldNilai3.getText());
            
            datamahasiswa.insertData(
                    TextFieldNIM.getText(), 
                    TextFieldNama.getText(), 
                    TextFieldAlamat.getText(), 
                    TextFieldMataKuliah.getText(), 
                    nilai1, 
                    nilai2, 
                    nilai3, 
                    nilai4, 
                    nilai5);
            viewDataTabel();
            ClearTextField();
        }catch (NumberFormatException e){
            System.out.println("Input nilai tidak valid, masukkan angka.");
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        datamahasiswa.deleteData(TableKRS.getSelectedRow());
        viewDataTabel();
    }//GEN-LAST:event_ButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerhitunganNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerhitunganNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerhitunganNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerhitunganNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerhitunganNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelMataKuliah;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNilai;
    private javax.swing.JLabel LabelNilai1;
    private javax.swing.JLabel LabelNilai3;
    private javax.swing.JLabel LabelNilai4;
    private javax.swing.JLabel LabelNilai5;
    private javax.swing.JTable TableKRS;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldMataKuliah;
    private javax.swing.JTextField TextFieldNIM;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNilai1;
    private javax.swing.JTextField TextFieldNilai2;
    private javax.swing.JTextField TextFieldNilai3;
    private javax.swing.JTextField TextFieldNilai4;
    private javax.swing.JTextField TextFieldNilai5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
